version: "2.2"
services:
  recv:
    image: ghcr.io/web-tech-tw/freya.recv:main
    container_name: freya-recv
    environment:
      APP_CONFIGURED: "1"
    env_file:
      - config.env
    networks:
      - sara
    ports:
      - 127.0.0.1:13060:3000
    volumes:
      - ../sara.recv/keypair_public.pem:/workplace/keypair_public.pem:ro
    restart: always

networks:
  sara:
    external:
      name: sara
